(()=>{
const palette=['#e96a4a','#f4c430','#ff9a3c','#2f80ed','#16a6a0','#d76b8a','#7a8fd8','#9a7b52','#6e9f63','#b16aaf','#5e8d9e','#a8795d'];
const defaults=['DUOLINGO','WORDS & PHRASES','CHECK & PRACTICE','READ & LISTEN','SPEAK'].map((name,i)=>({name,color:palette[i],minutes:10}));
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const slugify=v=>String(v||'').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,32);
const parts=location.pathname.split('/').filter(Boolean),base=parts[0]==='blokperblok'?'/blokperblok/':'/',route=slugify(parts[parts[0]==='blokperblok'?1:0]||'');
const key=s=>`blokperblok:lesson:${s}`,url=s=>base+s,read=s=>{try{return s?JSON.parse(localStorage.getItem(key(s))||'null'):null}catch{return null}};
const saved=read(route);let lessonName=saved?.lessonName||'',currentSlug=saved?route:'',withTransition=!!saved?.withTransition;
let blocks=saved?.blocks?.length?saved.blocks.slice(0,12).map((b,i)=>({name:String(b?.name||`LESBLOK ${i+1}`).slice(0,40),color:palette[i%palette.length],minutes:clamp(Math.round(+b?.minutes||10),1,60)})):defaults.map(x=>({...x}));
let index=0,total=blocks[0].minutes*60,remaining=total,running=false,lastTick=performance.now(),audioCtx=null,soundOn=true,lastBeep=null,lock=false;
const app=document.querySelector('.app'),steps=$('steps'),title=$('title'),label=$('blockLabel'),progress=$('progress'),next=$('next'),wrap=$('wrap'),startBtn=$('startBtn'),pauseBtn=$('pauseBtn'),summary=$('lessonSummary'),toggle=$('transitionToggle'),modal=$('modalBackdrop'),grid=$('editGrid'),countInput=$('blockCountInput'),totalInput=$('totalMinutesInput'),nameInput=$('lessonNameInput'),slugInput=$('lessonSlugInput'),savedList=$('savedLessonList'),screen=$('transitionScreen'),oldEl=$('transitionOld'),newEl=$('transitionNew'),metaEl=$('transitionMeta'),toast=$('toast'),soundDot=$('soundDot'),soundLabel=$('soundLabel');
const seconds=i=>blocks[i].minutes*60,mins=()=>blocks.reduce((s,b)=>s+b.minutes,0),notify=m=>{toast.textContent=m;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2800)};
function ensureCount(n){n=clamp(Math.round(+n||5),1,12);while(blocks.length<n){let i=blocks.length;blocks.push(defaults[i]?{...defaults[i]}:{name:`LESBLOK ${i+1}`,color:palette[i%palette.length],minutes:10})}blocks=blocks.slice(0,n);blocks.forEach((b,i)=>b.color=palette[i%palette.length])}
function distribute(t,n){n=clamp(Math.round(+n||5),1,12);t=clamp(Math.round(+t||50),n,240);ensureCount(n);let base=Math.floor(t/n),rest=t-base*n;blocks.forEach((b,i)=>b.minutes=base+(i<rest?1:0))}
function capture(){[...grid.querySelectorAll('.editRow')].forEach((r,i)=>{if(!blocks[i])return;let x=r.querySelectorAll('input');blocks[i].name=x[0].value.trim()||blocks[i].name;blocks[i].minutes=clamp(Math.round(+x[1].value||blocks[i].minutes),1,60)})}
function listSaved(){let a=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(!k?.startsWith('blokperblok:lesson:'))continue;try{let d=JSON.parse(localStorage.getItem(k)),s=k.replace('blokperblok:lesson:','');a.push({s,n:d?.lessonName||s})}catch{}}a.sort((x,y)=>x.n.localeCompare(y.n));savedList.innerHTML=a.length?'':'<span class="localNote">Nog geen lessen bewaard.</span>';a.forEach(x=>{let b=document.createElement('button');b.className='savedLessonLink';b.textContent=`${x.n} · /${x.s}`;b.onclick=()=>location.href=url(x.s);savedList.appendChild(b)})}
function editor(){nameInput.value=lessonName;slugInput.value=currentSlug;countInput.value=blocks.length;totalInput.value=mins();grid.innerHTML='';blocks.forEach((b,i)=>{let r=document.createElement('div');r.className='editRow';r.innerHTML=`<div class="rowNum">${i+1}</div><input type="text" maxlength="40" value="${b.name.replace(/"/g,'&quot;')}" aria-label="Naam lesblok ${i+1}"><div class="minutesWrap"><input class="minuteInput" type="number" min="1" max="60" step="1" value="${b.minutes}"> min</div>`;grid.appendChild(r)});grid.querySelectorAll('.minuteInput').forEach(x=>x.onchange=()=>{capture();totalInput.value=mins()});listSaved()}
function openEditor(){editor();modal.classList.add('show')}function closeEditor(){modal.classList.remove('show')}
function apply(){ensureCount(countInput.value);capture();lessonName=nameInput.value.trim();running=false;index=0;total=seconds(0);remaining=total;lastBeep=null;makeSteps();render()}
function save(){apply();let s=slugify(slugInput.value||lessonName);if(!s)return notify('Geef je les eerst een naam of adres.');currentSlug=s;localStorage.setItem(key(s),JSON.stringify({lessonName:lessonName||s,withTransition,blocks:blocks.map(({name,minutes})=>({name,minutes}))}));closeEditor();history.pushState({},'',url(s));notify(`Bewaard als rakkejak.be/blokperblok/${s}`)}
function makeSteps(){steps.innerHTML='';document.documentElement.style.setProperty('--block-count',blocks.length);blocks.forEach(()=>{let e=document.createElement('div');e.className='step';steps.appendChild(e)})}
function warning(){return withTransition&&remaining<=120&&remaining>0}
function render(){document.documentElement.style.setProperty('--accent',blocks[index].color);[...steps.children].forEach((e,i)=>{e.classList.toggle('active',i===index);e.classList.toggle('done',i<index);e.textContent=(i<index?'✓ ':'')+blocks[i].name});title.textContent=blocks[index].name;label.textContent=`Block ${index+1} of ${blocks.length}`;let pct=clamp((total-remaining)/total*100,0,100),warn=warning();progress.style.width=pct+'%';app.classList.toggle('transition-warning',warn);wrap.classList.toggle('show',warn);wrap.textContent=warn?'TRANSITIE · WERK AF':'WRAP UP';progress.style.background=warn?'#171717':(remaining<=15?'#c93d2e':blocks[index].color);next.innerHTML=index<blocks.length-1?`Next: <strong>${blocks[index+1].name}</strong>`:'<strong>End of lesson</strong>';startBtn.textContent=running?'RUNNING':remaining<total?'RESUME':'START';pauseBtn.disabled=!running;toggle.classList.toggle('active',withTransition);toggle.textContent=withTransition?'✓ MET TRANSITIE':'MET TRANSITIE';let equal=blocks.every(b=>b.minutes===blocks[0].minutes);summary.textContent=(equal?`${blocks.length} × ${blocks[0].minutes} min`:blocks.map(b=>b.minutes).join(' + ')+' min')+` · ${mins()} min totaal`}
function audio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function tone(f=720,d=.1,g=.055){if(!soundOn)return;audio();let o=audioCtx.createOscillator(),v=audioCtx.createGain(),n=audioCtx.currentTime;o.type='sine';o.frequency.value=f;v.gain.value=g;o.connect(v);v.connect(audioCtx.destination);v.gain.setValueAtTime(g,n);v.gain.exponentialRampToValueAtTime(.0001,n+d);o.start(n);o.stop(n+d)}
const pattern=n=>{for(let i=0;i<n;i++)setTimeout(()=>tone(760,.08,.05),i*115)};
function horn(){if(!soundOn)return;audio();let o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(410,n);o.frequency.linearRampToValueAtTime(320,n+.75);g.gain.setValueAtTime(.065,n);g.gain.exponentialRampToValueAtTime(.0001,n+.82);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(n+.85)}
function chime(){if(!soundOn)return;audio();let n=audioCtx.currentTime;[0,.11].forEach((d,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=i?830:620;g.gain.setValueAtTime(.0001,n+d);g.gain.exponentialRampToValueAtTime(.04,n+d+.015);g.gain.exponentialRampToValueAtTime(.0001,n+d+.18);o.connect(g);g.connect(audioCtx.destination);o.start(n+d);o.stop(n+d+.2)})}
function beeps(s){if(s===lastBeep)return;lastBeep=s;if([5,4,3].includes(s))pattern(1);if(s===2)pattern(2);if(s===1)pattern(3)}
async function advance(){if(lock)return;if(index>=blocks.length-1){running=false;render();return}lock=true;let ni=index+1;oldEl.textContent=blocks[index].name;newEl.textContent=blocks[ni].name;metaEl.textContent=`BLOCK ${ni+1} OF ${blocks.length}`;screen.style.setProperty('--next-accent',blocks[ni].color);screen.className='transitionScreen show phase1';await new Promise(r=>setTimeout(r,650));screen.classList.add('phase2');chime();await new Promise(r=>setTimeout(r,1050));index=ni;total=seconds(index);remaining=total;lastBeep=null;render();screen.classList.add('phase3');await new Promise(r=>setTimeout(r,700));screen.className='transitionScreen';await new Promise(r=>setTimeout(r,160));lock=false;running=true;lastTick=performance.now()}
function tick(now){let d=(now-lastTick)/1000;lastTick=now;if(running&&!lock){remaining-=d;if(remaining<=0){remaining=0;render();horn();running=false;advance()}else{beeps(Math.ceil(remaining));render()}}requestAnimationFrame(tick)}
function start(){audio();running=true;lastTick=performance.now();render()}function pause(){running=false;render()}function nextNow(){audio();running=false;remaining=0;render();horn();advance()}function reset(){running=false;index=0;total=seconds(0);remaining=total;lastBeep=null;render()}
countInput.onchange=()=>{capture();distribute(totalInput.value,countInput.value);editor()};totalInput.onchange=()=>{capture();distribute(totalInput.value,countInput.value);editor()};nameInput.oninput=()=>{if(!slugInput.dataset.touched)slugInput.value=slugify(nameInput.value)};slugInput.oninput=()=>{slugInput.dataset.touched='1';slugInput.value=slugify(slugInput.value)};
startBtn.onclick=start;pauseBtn.onclick=pause;$('plusBtn').onclick=()=>{total+=60;remaining+=60;blocks[index].minutes++;render()};$('nextBtn').onclick=nextNow;$('resetBtn').onclick=reset;toggle.onclick=()=>{withTransition=!withTransition;render();notify(withTransition?'Transitie-waarschuwing aan.':'Transitie-waarschuwing uit.')};$('soundToggle').onclick=()=>{soundOn=!soundOn;soundDot.classList.toggle('off',!soundOn);soundLabel.textContent=soundOn?'Sound on':'Sound off'};$('helpBtn').onclick=openEditor;$('closeModalBtn').onclick=closeEditor;$('saveEditBtn').onclick=save;$('useOnceBtn').onclick=()=>{apply();closeEditor();notify('Aangepaste les actief. Niet opgeslagen.')};$('resetExampleBtn').onclick=()=>{blocks=defaults.map(x=>({...x}));lessonName='';currentSlug='';withTransition=false;editor();render()};modal.onclick=e=>{if(e.target===modal)closeEditor()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEditor()});
makeSteps();render();requestAnimationFrame(tick);if(route&&!saved)setTimeout(()=>notify('Deze lokale les is niet op dit toestel bewaard. Je ziet het standaardvoorbeeld.'),400)
})();
