(() => {
  const palette = ['#e96a4a','#f4c430','#ff9a3c','#2f80ed','#16a6a0','#d76b8a','#7a8fd8','#9a7b52'];

  const defaultBlocks = [
    { name:'DUOLINGO',           color:palette[0], minutes:10 },
    { name:'WORDS & PHRASES',    color:palette[1], minutes:10 },
    { name:'CHECK & PRACTICE',   color:palette[2], minutes:10 },
    { name:'READ & LISTEN',      color:palette[3], minutes:10 },
    { name:'SPEAK',              color:palette[4], minutes:10 }
  ];

  function genericBlock(i){
    return { name:`LESBLOK ${i+1}`, color:palette[i % palette.length], minutes:10 };
  }
  function slugify(value){
    return String(value || '').toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,32);
  }

  const pathParts = location.pathname.split('/').filter(Boolean);
  const isProjectPath = pathParts[0] === 'blokperblok';
  const basePath = isProjectPath ? '/blokperblok/' : '/';
  const routeSlug = slugify(pathParts[isProjectPath ? 1 : 0] || '');
  const lessonUrl = slug => basePath + slug;

  const storageKey = slug => `blokperblok:lesson:${slug}`;
  function readLesson(slug){ if(!slug) return null; try{return JSON.parse(localStorage.getItem(storageKey(slug))||'null')}catch(e){return null} }
  const routeLesson=readLesson(routeSlug);
  let lessonName=routeLesson?.lessonName||'';
  let currentSlug=routeLesson?routeSlug:'';
  let blocks=routeLesson?.blocks?.length ? routeLesson.blocks.slice(0,8).map((b,i)=>({name:String(b?.name||defaultBlocks[i]?.name||`LESBLOK ${i+1}`).slice(0,40),color:palette[i%palette.length],minutes:Math.max(1,Math.min(60,Number(b?.minutes)||10))})) : defaultBlocks.map(b=>({...b}));
  const secondsFor=i=>Math.round(blocks[i].minutes*60);
  let index=0,total=secondsFor(0),remaining=total,running=false,lastTick=performance.now(),audioCtx=null,soundOn=true,lastBeepSecond=null,miniWin=null,transitionLock=false,compact=false;

  const $=id=>document.getElementById(id);
  const stepsEl=$('steps'),titleEl=$('title'),labelEl=$('blockLabel'),progressEl=$('progress'),nextEl=$('next'),wrapEl=$('wrap'),startBtn=$('startBtn'),pauseBtn=$('pauseBtn'),soundDot=$('soundDot'),soundLabel=$('soundLabel'),transitionScreen=$('transitionScreen'),transitionOld=$('transitionOld'),transitionNew=$('transitionNew'),transitionMeta=$('transitionMeta'),toast=$('toast'),helpBtn=$('helpBtn'),modalBackdrop=$('modalBackdrop'),editGrid=$('editGrid'),blockCountInput=$('blockCountInput'),lessonNameInput=$('lessonNameInput'),lessonSlugInput=$('lessonSlugInput'),savedLessonList=$('savedLessonList'),lessonSummary=$('lessonSummary');

  function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2800)}
  function normalizeCount(value){return Math.max(1,Math.min(8,Math.round(Number(value)||5)))}
  function ensureBlockCount(count){count=normalizeCount(count);while(blocks.length<count){const i=blocks.length;blocks.push(defaultBlocks[i]?{...defaultBlocks[i]}:genericBlock(i))}if(blocks.length>count)blocks=blocks.slice(0,count);blocks.forEach((b,i)=>b.color=palette[i%palette.length])}
  function captureRows(){[...editGrid.querySelectorAll('.editRow')].forEach((row,i)=>{if(!blocks[i])return;const inputs=row.querySelectorAll('input');blocks[i].name=inputs[0].value.trim()||blocks[i].name;blocks[i].minutes=Math.max(1,Math.min(60,Number(inputs[1].value)||blocks[i].minutes))})}
  function listSavedLessons(){const found=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key||!key.startsWith('blokperblok:lesson:'))continue;try{const data=JSON.parse(localStorage.getItem(key));const slug=key.replace('blokperblok:lesson:','');found.push({slug,name:data?.lessonName||slug})}catch(e){}}found.sort((a,b)=>a.name.localeCompare(b.name));savedLessonList.innerHTML='';if(!found.length){savedLessonList.innerHTML='<span class="localNote">Nog geen lessen bewaard.</span>';return}found.forEach(item=>{const el=document.createElement('button');el.className='savedLessonLink';el.textContent=`${item.name} · /${item.slug}`;el.addEventListener('click',()=>{location.href=lessonUrl(item.slug)});savedLessonList.appendChild(el)})}
  function buildEditor(){lessonNameInput.value=lessonName||'';lessonSlugInput.value=currentSlug||'';blockCountInput.value=blocks.length;editGrid.innerHTML='';blocks.forEach((b,i)=>{const row=document.createElement('div');row.className='editRow';row.innerHTML=`<div class="rowNum">${i+1}</div><input type="text" maxlength="40" value="${b.name.replace(/"/g,'&quot;')}" aria-label="Naam lesblok ${i+1}"><div class="minutesWrap"><input type="number" min="1" max="60" step="1" value="${b.minutes}" aria-label="Minuten lesblok ${i+1}"> min</div>`;editGrid.appendChild(row)});listSavedLessons()}
  function openEditor(){buildEditor();modalBackdrop.classList.add('show')} function closeEditor(){modalBackdrop.classList.remove('show')}
  function applyEditor(){ensureBlockCount(blockCountInput.value);captureRows();lessonName=lessonNameInput.value.trim();running=false;index=0;total=secondsFor(0);remaining=total;lastBeepSecond=null;makeSteps();render()}
  function useOnce(){applyEditor();closeEditor();showToast('Aangepaste les actief. Niet opgeslagen.')}
  function saveEditor(){applyEditor();let slug=slugify(lessonSlugInput.value||lessonName);if(!slug){showToast('Geef je les eerst een naam of adres.');return}currentSlug=slug;const payload={lessonName:lessonName||slug,blocks:blocks.map(({name,minutes})=>({name,minutes}))};localStorage.setItem(storageKey(slug),JSON.stringify(payload));closeEditor();showToast(`Bewaard als rakkejak.be/blokperblok/${slug}`);const target=lessonUrl(slug);if(location.pathname!==target)history.pushState({},'',target);listSavedLessons()}
  function restoreExample(){blocks=defaultBlocks.map(b=>({...b}));lessonName='';currentSlug='';buildEditor()}
  blockCountInput.addEventListener('change',()=>{captureRows();ensureBlockCount(blockCountInput.value);buildEditor()});lessonNameInput.addEventListener('input',()=>{if(!lessonSlugInput.dataset.touched)lessonSlugInput.value=slugify(lessonNameInput.value)});lessonSlugInput.addEventListener('input',()=>{lessonSlugInput.dataset.touched='1';lessonSlugInput.value=slugify(lessonSlugInput.value)});

  function makeSteps(){stepsEl.innerHTML='';document.documentElement.style.setProperty('--block-count',blocks.length);blocks.forEach(()=>{const el=document.createElement('div');el.className='step';stepsEl.appendChild(el)})}
  function setAccent(){document.documentElement.style.setProperty('--accent',blocks[index].color)}
  function render(){setAccent();[...stepsEl.children].forEach((el,i)=>{el.classList.toggle('active',i===index);el.classList.toggle('done',i<index);el.textContent=(i<index?'✓ ':'')+blocks[i].name});titleEl.textContent=blocks[index].name;labelEl.textContent=`Block ${index+1} of ${blocks.length}`;const elapsed=Math.max(0,total-remaining),pct=Math.min(100,Math.max(0,elapsed/total*100));progressEl.style.width=pct+'%';if(remaining<=60&&remaining>0){wrapEl.classList.add('show');progressEl.style.background=remaining<=15?'#c93d2e':blocks[index].color}else{wrapEl.classList.remove('show');progressEl.style.background=blocks[index].color}nextEl.innerHTML=index<blocks.length-1?`Next: <strong>${blocks[index+1].name}</strong>`:`<strong>End of lesson</strong>`;startBtn.textContent=running?'RUNNING':(remaining<total?'RESUME':'START');pauseBtn.disabled=!running;$('miniBtn').textContent=compact?'FULL':'MINI';lessonSummary.textContent=blocks.map(b=>b.minutes).every(m=>m===blocks[0].minutes)?`${blocks.length} × ${blocks[0].minutes} min`:blocks.map(b=>`${b.minutes}`).join(' + ')+' min';updateMini()}

  function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
  function tone(freq=720,duration=.10,gain=.055){if(!soundOn)return;ensureAudio();const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.value=freq;g.gain.value=gain;osc.connect(g);g.connect(audioCtx.destination);const now=audioCtx.currentTime;g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.start(now);osc.stop(now+duration)}
  function pattern(count){for(let i=0;i<count;i++)setTimeout(()=>tone(760,.08,.05),i*115)}
  function finalHorn(){if(!soundOn)return;ensureAudio();const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(410,audioCtx.currentTime);osc.frequency.linearRampToValueAtTime(320,audioCtx.currentTime+.75);g.gain.setValueAtTime(.065,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.82);osc.connect(g);g.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.85)}
  function nextChime(){if(!soundOn)return;ensureAudio();const now=audioCtx.currentTime;[0,.11].forEach((delay,i)=>{const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.value=i===0?620:830;g.gain.setValueAtTime(.0001,now+delay);g.gain.exponentialRampToValueAtTime(.04,now+delay+.015);g.gain.exponentialRampToValueAtTime(.0001,now+delay+.18);osc.connect(g);g.connect(audioCtx.destination);osc.start(now+delay);osc.stop(now+delay+.2)})}
  function beepLogic(sec){if(sec===lastBeepSecond)return;lastBeepSecond=sec;if(sec===5||sec===4||sec===3)pattern(1);if(sec===2)pattern(2);if(sec===1)pattern(3)}
  function tick(now){const delta=(now-lastTick)/1000;lastTick=now;if(running&&!transitionLock){remaining-=delta;if(remaining<=0){remaining=0;render();finalHorn();running=false;transitionToNext()}else{beepLogic(Math.ceil(remaining));render()}}requestAnimationFrame(tick)}
  async function transitionToNext(){if(transitionLock)return;if(index>=blocks.length-1){running=false;render();return}transitionLock=true;const nextIndex=index+1;transitionOld.textContent=blocks[index].name;transitionNew.textContent=blocks[nextIndex].name;transitionMeta.textContent=`BLOCK ${nextIndex+1} OF ${blocks.length}`;transitionScreen.style.setProperty('--next-accent',blocks[nextIndex].color);transitionScreen.classList.remove('phase1','phase2','phase3');transitionScreen.classList.add('show','phase1');await new Promise(r=>setTimeout(r,650));transitionScreen.classList.add('phase2');nextChime();await new Promise(r=>setTimeout(r,1050));index=nextIndex;total=secondsFor(index);remaining=total;lastBeepSecond=null;render();transitionScreen.classList.add('phase3');await new Promise(r=>setTimeout(r,700));transitionScreen.classList.remove('show','phase1','phase2','phase3');await new Promise(r=>setTimeout(r,160));transitionLock=false;running=true;lastTick=performance.now()}
  function start(){ensureAudio();running=true;lastTick=performance.now();render()} function pause(){running=false;render()} function nextNow(){ensureAudio();running=false;remaining=0;render();finalHorn();transitionToNext()} function reset(){running=false;index=0;total=secondsFor(index);remaining=total;lastBeepSecond=null;render()}
  function toggleCompact(){compact=!compact;document.body.classList.toggle('compact',compact);render();if(compact)showToast('Mini mode active. Resize this browser window if you want it beside your lesson material.')}
  function openMini(){try{miniWin=window.open('about:blank','_blank','popup=yes,width=470,height=190,left=50,top=50,resizable=yes,scrollbars=no')}catch(e){miniWin=null}if(!miniWin){showToast('Pop-up blocked. Allow pop-ups for this file, or use MINI mode instead.');return}const doc=miniWin.document;doc.open();doc.write(`<!doctype html><html><head><meta charset="utf-8"><title>Blok per Blok</title><style>html,body{margin:0;height:100%;font-family:Inter,system-ui,-apple-system,sans-serif;background:#fff;color:#171717}body{display:flex;align-items:center}.box{width:100%;padding:16px 18px 12px}.title{font-size:22px;font-weight:900;letter-spacing:-.025em;margin-bottom:10px}.bar{height:17px;border-radius:999px;background:#ececea;overflow:hidden}.fill{height:100%;width:0;border-radius:inherit;background:#e96a4a;transition:width .3s linear}.bottom{display:flex;justify-content:space-between;align-items:center;margin-top:9px;color:#777;font-size:12px}.controls{display:flex;gap:5px}button{border:0;border-radius:8px;padding:5px 8px;font:inherit;font-weight:800;background:#efefec;cursor:pointer}</style></head><body><div class="box"><div class="title" id="mt">DUOLINGO</div><div class="bar"><div class="fill" id="mf"></div></div><div class="bottom"><span id="mn">Next</span><span class="controls"><button id="mplus">+1</button><button id="mpause">II</button><button id="mnext">NEXT</button></span></div></div></body></html>`);doc.close();doc.getElementById('mplus').onclick=()=>$('plusBtn').click();doc.getElementById('mpause').onclick=()=>running?pause():start();doc.getElementById('mnext').onclick=()=>nextNow();updateMini();showToast('Detached mini timer opened.')}
  function updateMini(){if(!miniWin||miniWin.closed)return;try{const d=miniWin.document,mt=d.getElementById('mt'),mf=d.getElementById('mf'),mn=d.getElementById('mn');if(!mt||!mf||!mn)return;mt.textContent=blocks[index].name+(remaining<=60&&remaining>0?' · WRAP UP':'');const pct=Math.min(100,Math.max(0,(total-remaining)/total*100));mf.style.width=pct+'%';mf.style.background=remaining<=15?'#c93d2e':blocks[index].color;mn.textContent=index<blocks.length-1?'Next: '+blocks[index+1].name:'End of lesson';const p=d.getElementById('mpause');if(p)p.textContent=running?'II':'▶'}catch(e){}}

  startBtn.addEventListener('click',start);pauseBtn.addEventListener('click',pause);$('plusBtn').addEventListener('click',()=>{total+=60;remaining+=60;render()});$('nextBtn').addEventListener('click',nextNow);$('resetBtn').addEventListener('click',reset);$('miniBtn').addEventListener('click',toggleCompact);$('popBtn').addEventListener('click',openMini);$('soundToggle').addEventListener('click',()=>{soundOn=!soundOn;soundDot.classList.toggle('off',!soundOn);soundLabel.textContent=soundOn?'Sound on':'Sound off'});helpBtn.addEventListener('click',openEditor);$('closeModalBtn').addEventListener('click',closeEditor);$('saveEditBtn').addEventListener('click',saveEditor);$('useOnceBtn').addEventListener('click',useOnce);$('resetExampleBtn').addEventListener('click',restoreExample);modalBackdrop.addEventListener('click',e=>{if(e.target===modalBackdrop)closeEditor()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEditor()});
  makeSteps();render();if(routeSlug&&!routeLesson)setTimeout(()=>showToast('Deze lokale les is niet op dit toestel bewaard. Je ziet het Engelse voorbeeld.'),300);requestAnimationFrame(tick);
})();
